# Generated by Django 5.0.3 on 2024-04-04 09:50

import account.validators
import django.core.validators
import django.db.models.deletion
import django.db.models.manager
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='phone number must be 11 digits only!', regex='^\\d{11}')], verbose_name='username')),
                ('password', models.CharField(max_length=128, validators=[account.validators.validate_password], verbose_name='password')),
                ('email', models.EmailField(blank=True, max_length=80, null=True, validators=[django.core.validators.EmailValidator()], verbose_name='email')),
                ('first_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='firstname')),
                ('last_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='lastname')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('is_staff', models.BooleanField(default=False, verbose_name='is staff')),
                ('registered_time', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='registered time')),
                ('last_login', django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='last login')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_time', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='created time')),
                ('modified_time', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='modified time')),
                ('region', models.CharField(blank=True, max_length=32, null=True, verbose_name='region')),
                ('city', models.CharField(blank=True, max_length=32, null=True, verbose_name='city')),
                ('address_detail', models.TextField(blank=True, null=True, verbose_name='address detail')),
                ('fullname', models.CharField(blank=True, max_length=48, null=True, verbose_name='receiver fullname')),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True, verbose_name='receiver phone number')),
                ('zipcode', models.CharField(blank=True, max_length=24, null=True, verbose_name='zipcode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'address',
                'verbose_name_plural': 'addresses',
            },
            managers=[
                ('default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='BlockUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_time', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='created time')),
                ('modified_time', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='modified time')),
                ('phone_number', models.CharField(max_length=11, unique=True, verbose_name='phone number')),
                ('user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'blocked user',
                'verbose_name_plural': 'blocked users',
            },
            managers=[
                ('default_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
