# Generated by Django 3.2 on 2024-03-27 12:35

import django.core.validators
from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='phone number must be 11 digits only!', regex='^\\d{11}')], verbose_name='شماره موبایل')),
                ('password', models.CharField(max_length=128, verbose_name='رمز عبور')),
                ('email', models.EmailField(blank=True, max_length=80, null=True, validators=[django.core.validators.EmailValidator()], verbose_name='ایمیل')),
                ('first_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='نام')),
                ('last_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='نام خانوادگی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_staff', models.BooleanField(default=False, verbose_name='کارمند')),
                ('registered_time', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='ثبت نام')),
                ('last_login', django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='آخرین ورود')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
