# Generated by Django 5.0.3 on 2024-04-13 17:39

import django.db.models.manager
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_time', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='created time')),
                ('modified_time', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='modified time')),
                ('phone_number', models.CharField(max_length=11, null=True, verbose_name='phone number')),
            ],
            options={
                'verbose_name': 'login code',
                'verbose_name_plural': 'login codes',
            },
            managers=[
                ('default_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
