# Generated by Django 5.0.3 on 2024-04-13 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_logincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='last_otp',
            field=models.PositiveBigIntegerField(blank=True, editable=False, null=True, verbose_name='last otp'),
        ),
    ]
