# Generated by Django 5.0.3 on 2024-04-23 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_usermodel_last_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='human_id',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='human id'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='otp_try',
            field=models.PositiveSmallIntegerField(default=5, verbose_name='otp try number'),
        ),
    ]
