# Generated by Django 5.0.3 on 2024-04-24 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_usermodel_human_id_usermodel_otp_try'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_detail',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='address detail'),
        ),
    ]
