# Generated by Django 5.0.3 on 2024-04-05 09:52

import lib.base_model
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_color_name_alter_size_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=lib.base_model.CustomImageField(null=True, upload_to='products/', verbose_name='image'),
        ),
    ]
