# Generated by Django 3.2 on 2024-03-30 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_productimage_is_main'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name': 'color', 'verbose_name_plural': 'colors'},
        ),
        migrations.AlterField(
            model_name='attribute',
            name='title',
            field=models.CharField(max_length=48, verbose_name='attribute title'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(blank=True, max_length=48, null=True, verbose_name='category title'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='product title'),
        ),
    ]
