# Generated by Django 5.0.3 on 2024-04-10 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_productimage_image'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='product',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='buy_count',
            field=models.PositiveIntegerField(default=0, verbose_name='buy count'),
        ),
        migrations.AddField(
            model_name='product',
            name='visit_count',
            field=models.PositiveIntegerField(default=0, verbose_name='visit count'),
        ),
    ]
