# Generated by Django 5.0.3 on 2024-04-24 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(max_length=500, verbose_name='comment content'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='content',
            field=models.TextField(max_length=500, verbose_name='comment content'),
        ),
        migrations.AlterField(
            model_name='support',
            name='message',
            field=models.TextField(max_length=500, verbose_name='message'),
        ),
        migrations.AlterField(
            model_name='support',
            name='response',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='response'),
        ),
    ]
