# Generated by Django 3.2 on 2024-03-30 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='support',
            name='is_answered',
            field=models.BooleanField(default=False, verbose_name='answered'),
        ),
    ]
