# Generated by Django 5.0.3 on 2024-04-04 09:50

import django.db.models.deletion
import django.db.models.manager
import django_jalali.db.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('basket', '0001_initial'),
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_time', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='created time')),
                ('modified_time', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='modified time')),
                ('name', models.CharField(max_length=48, verbose_name='name')),
                ('merchant_id', models.CharField(max_length=48, verbose_name='merchant id')),
                ('request_url', models.URLField(verbose_name='request url')),
                ('verify_url', models.URLField(verbose_name='verify url')),
            ],
            options={
                'verbose_name': 'gateway',
                'verbose_name_plural': 'gateways',
            },
            managers=[
                ('default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_time', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='created time')),
                ('modified_time', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='modified time')),
                ('full_name', models.CharField(max_length=64, verbose_name='fullname')),
                ('phone_number', models.CharField(max_length=11, verbose_name='phone number')),
                ('address', models.TextField(verbose_name='address')),
                ('zipcode', models.CharField(max_length=16, verbose_name='zipcode')),
                ('package_price', models.PositiveIntegerField(verbose_name='package price')),
                ('shipping_price', models.PositiveIntegerField(verbose_name='shipping price')),
                ('discount_amount', models.PositiveIntegerField(verbose_name='discount amount')),
                ('total_amount', models.PositiveIntegerField(verbose_name='total amount')),
                ('tracking_code', models.CharField(max_length=64, verbose_name='tracking code')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buys', to=settings.AUTH_USER_MODEL)),
                ('gateway', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buys', to='order.gateway')),
            ],
            options={
                'verbose_name': 'buy',
                'verbose_name_plural': 'buys',
            },
            managers=[
                ('default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='BuyLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_time', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='created time')),
                ('modified_time', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='modified time')),
                ('quantity', models.PositiveSmallIntegerField(default=1, verbose_name='quantity')),
                ('product_price', models.PositiveIntegerField(verbose_name='product price')),
                ('buy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buy_lines', to='order.buy')),
                ('color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buy_lines', to='product.color')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buy_lines', to='product.product')),
                ('size', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buy_lines', to='product.size')),
            ],
            options={
                'verbose_name': 'buy line',
                'verbose_name_plural': 'buy lines',
            },
            managers=[
                ('default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_time', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='created time')),
                ('modified_time', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='modified time')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='account.address')),
                ('basket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='basket.basket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
            },
            managers=[
                ('default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_time', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='created time')),
                ('modified_time', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='modified time')),
                ('buy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='order.buy')),
            ],
            options={
                'verbose_name': 'refund',
                'verbose_name_plural': 'refunds',
            },
            managers=[
                ('default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_time', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='created time')),
                ('modified_time', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='modified time')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.PositiveIntegerField(verbose_name='amount')),
                ('authority', models.CharField(blank=True, max_length=48, null=True, verbose_name='authority code')),
                ('ref_id', models.CharField(blank=True, max_length=48, null=True, verbose_name='transaction number')),
                ('log', models.TextField(blank=True, null=True, verbose_name='log')),
                ('card_pan', models.CharField(blank=True, max_length=24, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True, verbose_name='phone number')),
                ('is_paid', models.BooleanField(default=False, editable=False, verbose_name='is paid')),
                ('ip', models.CharField(blank=True, editable=False, max_length=16, null=True, verbose_name='ip')),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='order.gateway')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='order.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'transaction',
                'verbose_name_plural': 'transactions',
            },
            managers=[
                ('default_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='buy',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buys', to='order.transaction'),
        ),
    ]
