# Generated by Django 5.0.3 on 2024-04-21 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gateway',
            name='start_pay_url',
            field=models.URLField(default=None, verbose_name='start pay url'),
            preserve_default=False,
        ),
    ]
