# Generated by Django 5.0.3 on 2024-04-22 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_gateway_start_pay_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='is_paid',
        ),
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'no information'), (2, 'paid'), (3, 'failed')], default=1, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='gateway',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='order.gateway'),
        ),
    ]
