# Generated by Django 5.0.3 on 2024-04-22 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_transaction_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='tracking_code',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='tracking code'),
        ),
    ]
