# Generated by Django 5.0.3 on 2024-04-22 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_buy_tracking_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy',
            name='refund',
            field=models.BooleanField(default=False, verbose_name='refund'),
        ),
        migrations.DeleteModel(
            name='Refund',
        ),
    ]
