# Generated by Django 5.0.3 on 2024-04-22 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_buy_refund_delete_refund'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'no information'), (2, 'paid'), (3, 'failed')], default=3, verbose_name='status'),
        ),
    ]
