# Generated by Django 5.0.3 on 2024-04-24 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_transaction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'همراه با خطا'), (2, 'موفق'), (3, 'ناموفق')], default=3, verbose_name='status'),
        ),
    ]
