# Generated by Django 5.0.3 on 2024-04-05 13:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storycategory',
            name='image',
            field=models.FileField(upload_to='storyCategory/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('jpg', 'jpeg', 'png'))], verbose_name='image'),
        ),
    ]
