# Generated by Django 5.0.3 on 2024-04-10 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_alter_storycategory_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='product',
        ),
    ]
